services:
  mysql:
    image: mysql:8.0
    container_name: mysql_api_church-mngt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: t00r
      MYSQL_DATABASE: church_mngt
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network

volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge
